### ISSUE TITLE
Providing JRE only archives

### ISSUE THREAD

**Issue by MichaIng** [adoptium/temurin17-binaries#1]
Is there a specific reason why no JRE only archives are provided anymore? Otherwise I hereby kindly ask for them. For running Java applications only the JRE is required and hence traffic and local overhead/space can be reduced by skipping the development parts.

**Comment by karianna** [comment]
See https://github.com/adoptium/temurin-build/issues/2683 and https://blog.adoptium.net/2021/10/jlink-to-produce-own-runtime/

We are revisiting the decision however, stay tuned if you _really_ need a JRE (but do try the jlinked runtime).
