### ISSUE TITLE
Java 17 for a 64-bit Raspbian OS

### ISSUE THREAD

**Issue by JMoreno97** [adoptium/temurin17-binaries#2]
Hello, I have a 64-bit Raspbian OS in my raspberry and I am trying to install java 17 64-bit. I downloaded "OpenJDK17U-jdk_x64_linux_hotspot_17.0.1_12.tar.gz" but when I try to execute java it says: "wrong executable format". 
What is happening? Am I doing something wrong?

Thanks.

**Comment by karianna** [comment]
Are Raspbian not ARM devices?  If so I think you want our ARM64 binary (not x64)
