### ISSUE TITLE
provide a "latest" release and prevent 3rd party scripts from containing a hardcoded outdated urls

### ISSUE THREAD

**Issue by cknoll** [adoptium/temurin17-binaries#4]
The guide https://techviewleo.com/how-to-install-temurin-openjdk-on-debian/ is really helpful. However, it contains a hardcoded wget command which points to  the outdated version `OpenJDK17U-jdk_x64_linux_hotspot_17.0.1_12.tar.gz`.

IMHO it would be best if there was a `...latest...`-file which always points to the latest released file. This would be for the benefit of documentation, dockerfiles etc.

**Comment by karianna** [comment]
You'll have to contact them directly on that.
