### ISSUE TITLE
OpenJDK17U-jdk_x86-32_windows_hotspot_17.0.1_12  can't work with android studio

### ISSUE THREAD

**Issue by bluecn2002** [adoptium/temurin17-binaries#6]
I have OS win 7 32bit.
using Temurin jdk_x86-32_windows_hotspot_17.0.1_12 .
it can't work with android studio 4.2.2,  Arctic Fox, bumblebee patch2. exceptions happens when open as.
AS 3.5.2 may dont work too (no sure now).

**Comment by bluecn2002** [comment]
hope Temurin jdk17 support AS bumblebee +

**Comment by karianna** [comment]
Please try 17.0.2 and post to adoptium-support repo if that fails
